apiVersion: v1
kind: Pod
metadata:
  name: api-pod
spec:
  containers:
  - name: api-container
    image: your-api-image:v1
    env:
    - name: DATABASE_URL
      value: "your_database_url"
    - name: API_KEY
      value: "your_api_key"
    - name: OTHER_SECRET
      valueFrom:
        secretKeyRef:
          name: secret-name
          key: other_secret_key
    # Add more environment variables as needed
