apiVersion: v1
kind: Pod
metadata:
  name: volume-mounts-pod
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}  # Creating an empty directory that lives as long as the Pod runs

  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80  # Exposing port 80 for Nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html  # Mounting the volume to Nginx's default HTML directory
    livenessProbe:
      httpGet:
        path: /  # Endpoint to check for liveness
        port: 80  # Port for liveness check
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /  # Endpoint to check for readiness
        port: 80  # Port for readiness check
      initialDelaySeconds: 10
      periodSeconds: 15

  - name: debian-container
    image: debian:latest
    command: ["sleep", "infinity"]  # Keeps the container running
    livenessProbe:
      exec:
        command: ["ls", "/data"]  # Custom command to check for liveness
      initialDelaySeconds: 20
      periodSeconds: 25
    readinessProbe:
      exec:
        command: ["ls", "/data"]  # Custom command to check for readiness
      initialDelaySeconds: 15
      periodSeconds: 20
    volumeMounts:
    - name: shared-volume
      mountPath: /data  # Mounting the volume to a directory in the Debian container
