apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
  - name: my-app-container
    image: my-app-image:latest
    ports:
    - containerPort: 80  # Replace with your app's port
    readinessProbe:
      httpGet:
        path: /healthz  # Replace with your app's readiness path
        port: 80  # Replace with your app's port
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /liveness  # Replace with your app's liveness path
        port: 80  # Replace with your app's port
      initialDelaySeconds: 20
      periodSeconds: 15
