apiVersion: v1
kind: Pod
metadata:
  name: your-pod-name
spec:
  containers:
  - name: your-container-name
    image: your-image
    env:
    - name: SECRET_KEY
      value: your-secret-value
    - name: OTHER_SECRET
      value: other-secret-value
    # Add more environment variables as needed
