apiVersion: v1
kind: Pod
metadata:
  name: api-pod
spec:
  containers:
  - name: api-container
    image: your-api-image:v1
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080 # Replace with your API port
    livenessProbe:
      httpGet:
        path: /health # Replace with your API's health check path
        port: 8080 # Replace with your API port
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /readiness # Replace with your API's readiness path
        port: 8080 # Replace with your API port
      initialDelaySeconds: 10
      periodSeconds: 15
