apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80  # Nginx default port
    # Add other Nginx container settings as needed

  - name: debian-container
    image: debian:latest
    command: ["sleep", "infinity"] # Keeps the container running
    # Add settings for the Debian container

  - name: redhat-container
    image: registry.access.redhat.com/ubi8/ubi:latest
    command: ["sleep", "infinity"] # Keeps the container running
    # Add settings for the RedHat container

  # Add more containers as needed
