apiVersion: v1
kind: Pod
metadata:
  name: readiness-liveness-probe-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80  # Exposing port 80 for Nginx
    readinessProbe:
      httpGet:
        path: /  # Endpoint to check for readiness
        port: 80  # Port for readiness check
      initialDelaySeconds: 15
      periodSeconds: 10  # Checking every 10 seconds after the initial delay
    livenessProbe:
      httpGet:
        path: /  # Endpoint to check for liveness
        port: 80  # Port for liveness check
      initialDelaySeconds: 20
      periodSeconds: 15  # Checking every 15 seconds after the initial delay
